default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  username: postgres
  password: ommitted
  port: 5432


development:
  <<: *default
  host: localhost
  database: db/development


test:
  <<: *default
  host: localhost
  database: db/test
